### GET request to example server
#GET https://examples.http-client.intellij.net/get
#    ?generated-in=IntelliJ IDEA

###

GET localhost:3000/good

###

GET localhost:3000/bad-client

###

GET localhost:3000/bad-server

###

GET localhost:3000/error

###

GET localhost:3000/json

###

GET localhost:3000/jsonp

###

GET localhost:3000/rand-error

###