### GET request to example server
#GET https://examples.http-client.intellij.net/get
#    ?generated-in=IntelliJ IDEA

###

GET localhost:3000/good

###

GET localhost:3000/bad-client

###

GET localhost:3000/bad-server

###

GET localhost:3000/error

###

GET localhost:3000/json

###

#GET localhost:3000/json-string

###

GET localhost:3000/jsonp

###

GET localhost:3000/rand-error

###

GET localhost:3000/admin/aaa

### GET settings
GET localhost:3000/settings

### PUT single setting
PUT localhost:3000/settings
Content-Type: application/json

{
  "name": "newKey",
  "value": "newValue"
}

### PUT multiple setting
PUT localhost:3000/settings
Content-Type: application/json

{
  "settings": [
    { "name": "newKeys1", "value": "newValues1" },
    { "name": "newKeys2", "value": "newValues2" }
  ]
}

###