### GET request to example server
#GET https://examples.http-client.intellij.net/get
#    ?generated-in=IntelliJ IDEA

###

GET localhost:3000/api/good

###

GET localhost:3000/api/bad-client

###

GET localhost:3000/api/bad-server

###

GET localhost:3000/api/error

###

GET localhost:3000/api/json

###

#GET localhost:3000/json-string

###

GET localhost:3000/api/jsonp

###

GET localhost:3000/api/rand-error

###

GET localhost:3000/admin/aaa

### GET config
GET localhost:3000/config

### PUT single setting
PUT localhost:3000/config
Content-Type: application/json

{
  "name": "newKey",
  "value": "newValue"
}

### PUT multiple setting
PUT localhost:3000/config
Content-Type: application/json

{
  "config": [
    { "name": "newKeys1", "value": "newValues1" },
    { "name": "newKeys2", "value": "newValues2" }
  ]
}

###